### ISSUE TITLE
rope.ml, rope.mli, and bm_ropes.ml license mismatch

### ISSUE THREAD

**Issue by andyli** [Chris00/ocaml-rope#3]
There is still a license mismatch that I missed:

The headers of rope.ml, rope.mli, and bm_ropes.ml state GPL, but the LICENSE.md file says LGPL.

**Comment by Chris00** [comment]
Do you need I make a new release?

**Comment by andyli** [comment]
Thanks! It would be nice, but I'm fine with applying the change as a patch on top of the current release.

**Comment by Chris00** [comment]
Release pending: https://github.com/ocaml/opam-repository/pull/11114
